# Generated by Django 4.2.10 on 2024-02-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
    ]
